package request;

public enum RequestType {
    NEEDS, NEEDING, CHARITIES, CHARITY, REGISTER_PERSON,
    REGISTER_CHARITY, DONATE, VALIDATE_DONATION, DONATIONS_MADE,
    DONATIONS_RECEIVED, DEBUG, PHOTO
}